apiVersion: v1
kind: Secret
metadata:
  name: yelp-secrets
  namespace: yelp
type: Opaque
data:
  JWT_SECRET_KEY: Y2hhbmdlbWUtc2VjcmV0LWtleQ==
  OPENAI_API_KEY: c2stcHJvai1ibXpQRnpuN0VOc3V2eXNHTmVlZlhCRk9mdC1CaEFTSHlpeGZPXzNGV2toUUozdFRIb1NMVDlySTMwMFJvX2NBeFF1c3BGRXoxaFQzQmxia0ZKUkxPazM1RGlwZG1nNExyeENuN05MVXI0REIwcXRvcVlJMlBzLVg4MmhzT1BHeEhNdGVfd09VdHlHRUhEV3E5bENBNzZERkMzVUE=
  TAVILY_API_KEY: dHZseS1kZXYtM2tZZnRrLWN2Zm9Yc0s1bUt6SXNQbE0xY051emtuRDdLcnFIbEU2SDZTVlpCcDdSRg==
